### ISSUE TITLE
selectbox::SelectBox not found

### ISSUE THREAD

**Issue by golanor** [ynqa/promkit#6]
Hi,

I'm trying to run the second example (the first one works), and I receive the following compilation error:
```rust
error[E0432]: unresolved import `promkit::selectbox`
 --> src/main.rs:6:55
  |
6 |     build::Builder, crossterm::style, Result, select, selectbox::SelectBox
  |                                                       ^^^^^^^^^ could not find `selectbox` in `promkit`
```
I'm working on version 0.1.1 on rust 1.62

**Comment by ynqa** [comment]
@golanor Aww, please use v0.1.2 which I just updated recently (sorry to add the breaking changes in the patch version).
